// import 'package:ehem_foundation_project/core/app_export.dart';import 'package:ehem_foundation_project/widgets/app_bar/appbar_leading_image.dart';import 'package:ehem_foundation_project/widgets/app_bar/appbar_subtitle.dart';import 'package:ehem_foundation_project/widgets/app_bar/custom_app_bar.dart';import 'package:ehem_foundation_project/widgets/custom_elevated_button.dart';import 'package:ehem_foundation_project/widgets/custom_icon_button.dart';import 'package:ehem_foundation_project/widgets/custom_outlined_button.dart';import 'package:flutter/material.dart';class AllAttachmentsDeleteOneScreen extends StatelessWidget {const AllAttachmentsDeleteOneScreen({Key? key}) : super(key: key);
//
// @override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: appTheme.gray100.withOpacity(0.5), appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 8.v), child: Column(children: [_buildFileName(context), SizedBox(height: 24.v), _buildFrame1(context), SizedBox(height: 5.v)])))); }
// /// Section Widget
// PreferredSizeWidget _buildAppBar(BuildContext context) { return Opacity(opacity: 0.4, child: CustomAppBar(height: 64.v, leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 16.h, top: 24.v, bottom: 16.v), onTap: () {onTapArrowLeft(context);}), title: AppbarSubtitle(text: "Attachments", margin: EdgeInsets.only(left: 15.h)), styleType: Style.bgFill_1)); }
// /// Section Widget
// Widget _buildPlaylist(BuildContext context) { return Opacity(opacity: 0.4, child: CustomElevatedButton(height: 96.v, width: 99.h, text: "File name", rightIcon: Container(padding: EdgeInsets.all(1.h), margin: EdgeInsets.only(left: 14.h), decoration: BoxDecoration(color: appTheme.gray100.withOpacity(0.5), borderRadius: BorderRadius.circular(4.h)), child: CustomImageView(imagePath: ImageConstant.imgThumbsUp, height: 13.v, width: 12.h)), buttonStyle: CustomButtonStyles.none, decoration: CustomButtonStyles.gradientOnErrorContainerToOnPrimaryContainerTL12Decoration, buttonTextStyle: CustomTextStyles.bodySmallGray10012)); }
// /// Section Widget
// Widget _buildClientTestimonials(BuildContext context) { return Opacity(opacity: 0.4, child: CustomElevatedButton(height: 96.v, width: 98.h, text: "File name", rightIcon: Container(padding: EdgeInsets.all(1.h), margin: EdgeInsets.only(left: 14.h), decoration: BoxDecoration(color: appTheme.gray100.withOpacity(0.5), borderRadius: BorderRadius.circular(4.h)), child: CustomImageView(imagePath: ImageConstant.imgThumbsUp, height: 13.v, width: 12.h)), buttonStyle: CustomButtonStyles.none, decoration: CustomButtonStyles.gradientOnErrorContainerToOnPrimaryContainerTL12Decoration, buttonTextStyle: CustomTextStyles.bodySmallGray10012)); }
// /// Section Widget
// Widget _buildFileName(BuildContext context) { return Column(children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [_buildRecentOrders(context, fileName: "File name"), Opacity(opacity: 0.4, child: Container(padding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 1.v), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder12, image: DecorationImage(image: AssetImage(ImageConstant.imgFrame92047), fit: BoxFit.cover)), foregroundDecoration: AppDecoration.gradientOnErrorContainerToOnPrimaryContainer1.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 6.v), Align(alignment: Alignment.centerRight, child: Container(height: 16.adaptSize, width: 16.adaptSize, padding: EdgeInsets.all(1.h), decoration: AppDecoration.fillGray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: CustomImageView(imagePath: ImageConstant.imgThumbsUp, height: 13.v, width: 12.h, alignment: Alignment.center))), SizedBox(height: 52.v), Text("File name", style: CustomTextStyles.bodySmallGray10012)]))), _buildRecentOrders(context, fileName: "File name")]), SizedBox(height: 16.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [_buildPlaylist(context), _buildClientTestimonials(context), Opacity(opacity: 0.4, child: Container(padding: EdgeInsets.symmetric(horizontal: 13.h, vertical: 22.v), decoration: AppDecoration.outlineOnError.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [Text("Add Attacment", style: CustomTextStyles.bodySmallOnError), SizedBox(height: 8.v), CustomIconButton(height: 24.adaptSize, width: 24.adaptSize, padding: EdgeInsets.all(1.h), child: CustomImageView(imagePath: ImageConstant.imgCarbonAddFilled))])))])]); }
// /// Section Widget
// Widget _buildReviews(BuildContext context) { return Expanded(child: CustomElevatedButton(text: "Delete", margin: EdgeInsets.only(right: 4.h), buttonStyle: CustomButtonStyles.fillPrimaryContainer, buttonTextStyle: CustomTextStyles.titleSmallGray100)); }
// /// Section Widget
// Widget _buildDoctorReviews(BuildContext context) { return Expanded(child: CustomOutlinedButton(height: 40.v, text: "Cancel", margin: EdgeInsets.only(left: 4.h), buttonStyle: CustomButtonStyles.outlineOnError)); }
// /// Section Widget
// Widget _buildFrame1(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 11.v), decoration: AppDecoration.background.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(width: 193.h, child: Text("Are you sure you want to delete this attachment", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.titleSmall!.copyWith(height: 1.71))), SizedBox(height: 12.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildReviews(context), _buildDoctorReviews(context)]), SizedBox(height: 12.v)])); }
// /// Common widget
// Widget _buildRecentOrders(BuildContext context, {required String fileName, }) { return Opacity(opacity: 0.4, child: Container(padding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 1.v), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder12, image: DecorationImage(image: AssetImage(ImageConstant.imgFrame92048), fit: BoxFit.cover)), foregroundDecoration: AppDecoration.gradientOnErrorContainerToOnPrimaryContainer1.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 6.v), Align(alignment: Alignment.centerRight, child: Container(height: 16.adaptSize, width: 16.adaptSize, padding: EdgeInsets.all(1.h), decoration: AppDecoration.fillGray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: CustomImageView(imagePath: ImageConstant.imgThumbsUp, height: 13.v, width: 12.h, alignment: Alignment.center))), SizedBox(height: 52.v), Text(fileName, style: CustomTextStyles.bodySmallGray10012.copyWith(color: appTheme.gray100))]))); }
//
// /// Navigates back to the previous screen.
// onTapArrowLeft(BuildContext context) { Navigator.pop(context); }
//  }
